---
- hosts: appserver
  become: true
  pre_tasks:
     - name: apt-get update
       apt:
         update_cache: true
  vars:
    USER: ip-10-100-0-47
  tasks:
     - name: install apt packages
       apt: 
         name: 
           - apt-transport-https 
           - ca-certificates 
           - curl 
           - gnupg-agent 
           - software-properties-common
         state: latest
       become: true
     - name: add docker's official GPG key
       apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
       become: true
     - name: fingerprint
       command: 'apt-key fingerprint 0EBFCD88'
       become: true
     - name: setup stable repo
       shell: lsb_release -cs
       register: ubuntu_version
     - name: Add Docker Repository
       command: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"'
       become: true
     - name: update apt packages
       apt: 
         update_cache: "yes"
         force_apt_get: "yes"
     - name: install docker
       apt:
         name: docker-ce
       become: true
     - name: create docker group to run docker without sudo
       group:
          name: "docker"
          state: present
     - name: add user to docker
       user:
         name: "{{ USER }}"
         groups: "docker"
         append: "yes"
