---
- name: first ansible playbook
  hosts: all
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start apache2 service
      service:
        name: apache2
        state: restarted
    - command: echo "Installed apache2 and service is running now!"
